### ISSUE TITLE
Error while loading saved model

### ISSUE THREAD

**Issue by rgsatish** [CBIIT/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor#4]
Error in loading saved model, while executing the command below:
python uno_infer2.py --train_sources CTRP GDSC NCI60 SCL SCLC ALMANAC  --use_landmark_genes True --preprocess_rnaseq source_scale --no_feature_source True --no_response_source True --test_sources gCSI  

**Error:**
Traceback (most recent call last):
  File "uno_infer2.py", line 581, in <module>
    main()
  File "uno_infer2.py", line 577, in main
    run(params)
  File "uno_infer2.py", line 394, in run
    loaded_model_json.load_weights(trained_model_h5)
  File "/data/ranganathangas2/conda/envs/UNO/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/data/ranganathangas2/conda/envs/UNO/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/data/ranganathangas2/conda/envs/UNO/lib/python3.7/site-packages/keras/engine/saving.py", line 1183, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by rgsatish** [comment]
**Rectification**

Based on the suggestions  from George (https://github.com/keras-team/keras/issues/14265). "**h5py=2.10.0**" was added to the conda file (environment.yaml) file. And this rectified the issue.
$environment.yaml
name: UNO
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy=4.0.1
  - keras-gpu=2.3.1
  - matplotlib=3.3.4
  - numba=0.53.1
  - numpy=1.19.2
  - patsy=0.5.1
  - pandas=1.1.3
  - python=3.7
  - requests=2.25.1
  - scikit-learn=0.24.1
  - statsmodels=0.11.0
  - tensorflow=1.15.0
  - tqdm=4.59.0
  - **h5py=2.10.0**
