### ISSUE TITLE
Error running python uno_baseline_keras2.py --train_sources gCSI --cache cache/gCSI --use_landmark_genes True --preprocess_rnaseq source_scale --no_feature_source True --no_response_source True

### ISSUE THREAD

**Issue by Adenugakolade-02** [CBIIT/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor#6]
Using TensorFlow backend.
Traceback (most recent call last):
  File "uno_baseline_keras2.py", line 21, in <module>
    import uno as benchmark
  File "/mnt/c/projects/data_str/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor/pilot1/Uno/uno.py", line 18, in <module>
    import candle
  File "/mnt/c/projects/data_str/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor/common/candle/__init__.py", line 5, in <module>
    from benchmark_def import Benchmark
  File "/mnt/c/projects/data_str/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor/common/benchmark_def.py", line 13, in <module>
    import parsing_utils
ModuleNotFoundError: No module named 'parsing_utils'

**Comment by darkestfloyd** [comment]
Some of the util files are missing in this repo, there is an open pull request [1] that fixes this issue. I manually cloned the repo mentioned in the pull request and copied the files. Can confirm that the model trains as expected.

[1] https://github.com/CBIIT/NCI-DOE-Collab-Pilot1-Unified-Drug-Response-Predictor/pull/5/files

**Comment by jonesse3** [comment]
@darkestfloyd Thank you for your comment! @Adenugakolade-02 I have merged the pull request that fixes the issue. I ran the command line you used, and the model ran successfully for me. Let me know if you have any other issues running the code.
